<a href="https://colab.research.google.com/github/Nurdaylight/A-Karpathy-repl/blob/main/12_01_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
%matplotlib inline

In [63]:
probs = torch.tensor([
    [0.1, 0.32, 0.3],
    [0.2, 0.2, 0.6],
    [0.8, 0.1, 0.1],
    [0.3, 0.4, 0.3],
    [0.5, 0.2, 0.3],
])

ys = torch.tensor([1, 1, 1, 1, 1])

print(probs[torch.arange(5), ys])

tensor([0.3200, 0.2000, 0.1000, 0.4000, 0.2000])


In [154]:
import urllib.request

url = "https://raw.githubusercontent.com/karpathy/makemore/refs/heads/master/names.txt"
filename = 'names.txt'

with urllib.request.urlopen(url) as f:
    data = f.read().decode("utf-8")

words= data.splitlines()


In [132]:
chars=sorted(set(".".join(words)))
stoi={j:i for i,j in enumerate(chars)}
print(chars)
stoi["."]

['.', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


0

In [155]:
context=3
words=["."*context+word+"."for word in words]

In [110]:
#dont think below is necessary looking back

#Make mappings of context of 3 to next predicted letter. For each word. Aka data X and data Y.
#lets replace whole data with numbers
num_words=[stoi[i] for word in words for i in word]
num_words[:5]

[0, 0, 0, 5, 13]

In [188]:
X_str=[word[i:i+context] for word in words for i in range(0,len(word)-context)]
Y=[stoi[word[i+context]] for word in words  for i in range(0,len(word)-context)]

X=[stoi[x] for val in X_str for x in val]
X=torch.tensor(X).reshape(-1,3)
Y=torch.tensor(Y)


In [189]:
print(X[0],Y[0])

tensor([0, 0, 0]) tensor(5)


In [191]:
X.shape

torch.Size([32, 3])

In [197]:
C=torch.randn((27,2))
C

tensor([[-0.6931, -1.0699],
        [ 0.7534, -0.1407],
        [-1.4342,  0.1588],
        [ 0.4333, -1.4680],
        [-0.7269,  0.5189],
        [-0.2004,  0.2108],
        [ 1.0264,  0.1379],
        [ 0.1913, -0.6981],
        [ 0.2115,  1.0344],
        [ 1.0630, -1.7731],
        [-1.3849,  0.7819],
        [-0.1568, -1.6967],
        [-1.9668,  0.6010],
        [ 0.4028,  3.0372],
        [ 1.0473,  0.1679],
        [-0.6142,  0.1624],
        [ 0.2870, -1.1595],
        [ 0.3714, -1.0903],
        [ 1.0591, -1.0420],
        [-0.5743, -0.6770],
        [ 0.6397, -1.0174],
        [ 0.1560,  2.3585],
        [ 0.0943, -0.5863],
        [-0.4717, -0.0424],
        [ 0.8466,  1.9036],
        [-0.0633, -0.3181],
        [ 0.7465, -0.6759]])

In [232]:
emb = C[X]
W1=torch.randn([6,100])
b1=torch.randn(100)

In [235]:
h = torch.tanh(emb.view(-1,6)@W1+b1)
h.shape

torch.Size([32, 100])

In [236]:
h

tensor([[ 0.6632,  0.9993, -0.3293,  ...,  0.9954,  0.9779,  0.9996],
        [ 0.2762,  0.9983, -0.9871,  ...,  0.9996,  0.5948,  0.9996],
        [-0.7636,  0.8030, -1.0000,  ...,  0.9973, -0.9827,  0.9805],
        ...,
        [ 0.9830,  0.6377, -0.9884,  ...,  0.9427, -0.2702,  0.9706],
        [ 0.3621,  0.9955,  0.9554,  ..., -0.9769, -0.9594, -0.7406],
        [ 1.0000, -0.2291,  0.5998,  ..., -0.4945, -0.8312, -0.3474]])

In [238]:
W2=torch.randn(100,27)
b2=torch.randn(27)

In [239]:
logits= (h@W2+b2)

In [287]:
prob=torch.softmax(logits,dim=1)
prob.sum()

tensor(32.)

In [277]:
softs= logits.exp()/(logits.exp().sum(1,keepdims=True))

In [289]:
softs[0].sum()

tensor(1.0000)

In [290]:
Y

tensor([ 5, 13, 13,  1,  0, 15, 12,  9, 22,  9,  1,  0,  1, 22,  1,  0,  9, 19,
         1,  2,  5, 12, 12,  1,  0, 19, 15, 16,  8,  9,  1,  0])

In [297]:
prob[torch.arange(len(Y)),Y]

tensor([5.5227e-01, 9.3123e-03, 3.3784e-08, 1.2944e-16, 3.2208e-06, 1.4989e-05,
        3.9808e-08, 1.4749e-08, 7.8501e-08, 2.1398e-12, 3.4127e-02, 3.9174e-16,
        3.7045e-02, 9.6913e-01, 2.5211e-03, 3.0986e-09, 1.1932e-07, 1.1494e-10,
        2.8145e-01, 1.0738e-02, 1.9225e-02, 1.5524e-08, 4.9938e-13, 1.4122e-09,
        1.0017e-04, 1.5520e-14, 7.3837e-04, 9.0214e-03, 1.0789e-11, 7.1970e-04,
        2.3144e-06, 7.0076e-07])