<a href="https://colab.research.google.com/github/Nurdaylight/A-Karpathy-repl/blob/main/Learning_class_structures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
from dataclasses import dataclass

import torch
import torch.nn as nn
import torch.nn.functional as F


In [8]:
@dataclass
class GPTconfig:
    sequence_len: int = 2048
    vocab_size: int = 32768
    n_layer: int = 12
    n_head: int = 6 # number of query heads
    n_kv_head: int = 6 # number of key/value heads (GQA)
    n_embd: int = 768  # C

    window_pattern: str = "SSSL" # repeated pattern

In [16]:

def norm(x):
    # Purely functional rmsnorm with no learnable params
    return F.rms_norm(x, (x.size(-1),))


In [41]:
x=torch.randn(3,7)*1000


In [55]:
x

tensor([[ -646.7415,   125.4885,  -404.6364,  -717.0774,  1244.1007,  1333.2919,
          1543.0557],
        [-1088.4598,  1092.7404,   751.0924,   656.5969, -1559.8136,    84.6563,
           918.3719],
        [-1086.7582,   838.9219,   959.5722,  -265.1540,   342.1288,   779.7300,
         -1005.3425]])

In [161]:
x2=(x**2)
x2=x2.sum(1)
x2=1/7*x2
x2=x2**0.5
x2=x.T/x2

In [162]:
torch.allclose(norm(x),x2.T)

True

In [159]:
norm(x)

tensor([[-0.6553,  0.1271, -0.4100, -0.7266,  1.2606,  1.3509,  1.5635],
        [-1.1161,  1.1205,  0.7702,  0.6733, -1.5994,  0.0868,  0.9417],
        [-1.3389,  1.0336,  1.1822, -0.3267,  0.4215,  0.9606, -1.2386]])

In [160]:
x2.T

tensor([986.9453, 975.2420, 811.6705])

In [120]:
(1/len(x[:,0]))*((x**2).sum(1))**0.5

tensor([870.4039, 860.0826, 715.8261])